init:
  - git config --global core.autocrlf true

image:
- Visual Studio 2017
- Ubuntu

install:
  - ps: Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser

build: false

before_test:
  - ps: Import-Module .\ClipboardText.psd1 -Force

# Invoke Pester to run all of the unit tests, then save the results into XML in order to populate the AppVeyor tests section
test_script:
  - ps: $res = Invoke-Pester -Path '.\Tests' -OutputFormat NUnitXml -OutputFile .\Tests\TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Tests\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
